product = "Angry Birds Lite"
publisher = "Rovio"
name = "Angry Birds Lite"
width = 864
height = 480
orientation = 0
datapath = "data"
imagePath = "images"
fontPath = "fonts"
audioPath = "audio"
localizationPath = "localization"
levelPath = "levels"
scriptPath = "scripts"
deviceModel = "android"
fullscreen = false
showCursor = true
isLiteVersion = true
isBetaVersion = true
